start post-O2 configuration
ligo-cbc/pycbc-config pull request #14
Opened 2017-08-28 07:11 UTC by ahnitz

Start a new config file for post O2. This removes requirement on science intent, and lowers the SNR threshold, though in practice this is limited by the triggers per batch.

2017-08-28 12:48 UTC, duncan-brown commented
@ahnitz check with @stuartthebruce what the postO2 data name is going to be. I don't think it's ER13.

2017-08-28 14:34 UTC, bbockelm commented
@stuartthebruce @duncan-brown - would you like the directory sync'd to CVMFS once it is transferred to Nebraska?  I've got the top-level directories on a whitelist still...

2017-08-28 22:29 UTC, stuartthebruce commented
The post-O2 data will be archived in the directories where O2/ is replaced with postO2/.

I don't see any need to transfer those to Nebraska or CVMFS as both LIGO Observatories are going to vent key parts of their vacuum chambers for extended commissioning work, i.e., no instrument sensitive to gravitational waves for many months.

2017-08-28 23:14 UTC, duncan-brown commented
@bbockelm what @stuartthebruce said. This is just to keep the low-latency ticking over.

2017-09-06 16:56 UTC, titodalcanton requested changes
@ahnitz the changes look ok, but could you rename the directory from ER13 to postO2?

2018-01-16 09:51 UTC, spxiwh commented
Should this now be closed?

2018-01-16 14:43 UTC, tdent commented
Ian do you mean closed as in abandoned, or as in merged?

2018-01-16 14:45 UTC, closed without merging

2018-01-16 15:07 UTC, spxiwh commented
Abandoned.