Add new format example config file
ligo-cbc/pycbc-config pull request #55
Opened 2019-06-05 14:32 UTC by spxiwh

This would replace the old-format DQ.ini. This should provide an example of what is needed if running on older data as well.

2019-06-07 20:50 UTC, tdent commented on O3exp/pipeline/data_O3_C00.ini
> +v1-channel-name = V1:Hrec_hoft_16384Hz
Not clear why V1 is not commented out here as it is in ifos. Add a comment explaining that the V1 options here are ignored unless turned on in ifos.

In general prefer not to have options that are ignored, but convenience may override that here

2019-06-07 20:50 UTC, tdent commented on O3exp/pipeline/data_O3_C00.ini
> +;datafind-check-frames-exist = no_test
This line is cryptic, remove or explain more

2019-06-07 20:50 UTC, tdent commented on O3exp/pipeline/data_O3_C00.ini
> +
Remove empty line...

2019-06-11 08:00 UTC, spxiwh commented
Changes made as requested

2019-06-11 08:27 UTC, tdent commented
Actually I'm still a bit confused as to what this folder is for. In the past we have used it for runs on *O2* data to develop / test for O3. I think that is still its main purpose, though it won't hurt to have an *example* file for O3 which we don't use for production.
So, please make sure there is a viable data.ini for O2 C02 clean data, as this is what our benchmark runs have used up to now.

2019-06-11 15:46 UTC, spxiwh commented
@tdent I've added a O2 CO2 data.ini file, and also removed the old files, which now won't work.

I also decided to have Virgo active by default in both the O2 and O3 example ini files.

2019-06-11 15:50 UTC, tdent commented on O3exp/pipeline/data_O3_C00.ini
> +segments-vetoes = -CAT_2,-CAT_H
as above, minus or plus?

2019-06-11 15:50 UTC, tdent commented on O3exp/pipeline/data_O3_C00.ini
> +v1=
as above, add comment for how to turn off V1

2019-06-11 15:50 UTC, tdent requested changes
thanks, see minor comments and check the veto signs!

2019-06-11 16:43 UTC, spxiwh commented
Argh, I keep getting the `-`s wrong. Should be fixed now.

2019-06-11 17:15 UTC, tdent approved these changes

2019-06-11 17:16 UTC, merged